on:
  push:
    branches:
    - master

jobs:
  e2e-tests:
    runs-on: windows-latest # or macos-latest, ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install && npx playwright install
      - name: Run your tests
        run: npm test
